### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by quaintdev** [mathenz/goffy#1]
First of all thank you for creating this utility and sharing it.

I was trying to install using the command in documentation I am getting below error

```
go: 'go install' requires a version when current directory is not in a module
	Try 'go install github.com/mathenz/goffy@latest' to install the latest version
```

Any suggestions?

**Comment by mathenz** [comment]
Hi, thanks for reporting this.

Did you specify "@latest" in the command?

**Comment by quaintdev** [comment]
Hey Hi

Yes I had added @latest in command

Thanks



________________________________

**Comment by quaintdev** [comment]
Sorry for confusion the actual error I got initially was this. The latest related error came after I tried without @latest

```
go: downloading github.com/mathenz/goffy v1.0.2
go: github.com/mathenz/goffy@latest (in github.com/mathenz/goffy@v1.0.2): go.mod:3: invalid go version '1.21.0': must match format 1.23
```

**Comment by mathenz** [comment]
Oh, I see. I'll try something.

By the way, does it work if you install it from the 'latest releases' section?

**Comment by quaintdev** [comment]
Yes I can run binary without issue


________________________________

**Comment by mathenz** [comment]
Hey, @quaintdev 

What version do you get when you run 'go version'?

**Comment by mathenz** [comment]
I changed the version to 1.20 due to formatting problems with '1.21.0'. I can install the program on my machine without issue. Could you try it again?
