### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by francqz31** [mathenz/goffy#5]
Hey amazing tool , it worked off the bat. and so easy to use , but where does it get the music from ? all the music downloaded are 127-128kbps m4a!  they are stereo 44.1khz 32-bit but the kbps is too low. I guess you take the id from spotify and scrape from youtube music ? i heard some people do the same but with deezer but deezer gets really high quality

**Comment by mathenz** [comment]
Yes, like you said.

There is a way to get a bit-rate of 256 Kbps, but the file size would increase considerably, so I tried to keep a balance between quality and size.

By the way, thank you.

**Comment by francqz31** [comment]
oh ok no problems , last thing , would you consider 320kbps option ? or something around deezer api? , idk what max quality youtube music has 
edit: i just googled it , youtube music max quality is 256kbps , yeah i think i will try to find a deezer solution myself

**Comment by mathenz** [comment]
Yes, that is the maximum. Although, in the future I might add a feature to goffy that allows you to download audios with a bit-rate of 256 Kbps, targeting people who don't care about file size.
